---
title: "Fig6_CD4diff"
author: "Nils Eling"
date: "30/08/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CD4 T cell differentiation

Read in genenames and load libraries.

```{r}
library(BASiCS)
library(cowplot)
mouse.genes <- read.table("Data/Genenames.txt", sep = '\t', header = TRUE, stringsAsFactors = FALSE)
rownames(mouse.genes) <- mouse.genes[,1]
```

```{r}
MCMCs <- readRDS("Results/Differential_testing/All_CD4diff.rds")

Test.day2_vs_day4 <- BASiCS_TestDE(Chain1 = MCMCs$day4, Chain2 = MCMCs$day2, 
                                   EpsilonM = 1, OffSet = TRUE, 
                                   GroupLabel2 = "Day2", GroupLabel1 = "Day4",
                                   Plot = FALSE, PlotOffset = FALSE, OrderVariable = "GeneName")

Test.day2_vs_day4.logFC0 <- BASiCS_TestDE(Chain1 = MCMCs$day4, Chain2 = MCMCs$day2, 
                                          EpsilonM = 0, OffSet = TRUE,
                                          GroupLabel2 = "Day2", GroupLabel1 = "Day4",
                                          Plot = FALSE, PlotOffset = FALSE, OrderVariable = "GeneName")

Test.day4_vs_day7 <- BASiCS_TestDE(Chain1 = MCMCs$day7, Chain2 = MCMCs$day4, 
                                   EpsilonM = 1, OffSet = TRUE, 
                                   GroupLabel2 = "Day4", GroupLabel1 = "Day7",
                                   Plot = FALSE, PlotOffset = FALSE, OrderVariable = "GeneName")

Test.day4_vs_day7.logFC0 <- BASiCS_TestDE(Chain1 = MCMCs$day7, Chain2 = MCMCs$day4, 
                                          EpsilonM = 0, OffSet = TRUE,
                                          GroupLabel2 = "Day4", GroupLabel1 = "Day7",
                                          Plot = FALSE, PlotOffset = FALSE, OrderVariable = "GeneName")

Test.day2_vs_day7 <- BASiCS_TestDE(Chain1 = MCMCs$day7, Chain2 = MCMCs$day2, 
                                   EpsilonM = 1, OffSet = TRUE, 
                                   GroupLabel2 = "Day2", GroupLabel1 = "Day7",
                                   Plot = FALSE, PlotOffset = FALSE, OrderVariable = "GeneName")

Test.day2_vs_day7.logFC0 <- BASiCS_TestDE(Chain1 = MCMCs$day7, Chain2 = MCMCs$day2, 
                                   EpsilonM = 0, OffSet = TRUE, 
                                   GroupLabel2 = "Day2", GroupLabel1 = "Day7",
                                   Plot = FALSE, PlotOffset = FALSE, OrderVariable = "GeneName")


Sig.2_4 <- Test.day2_vs_day4$TableResDisp[Test.day2_vs_day4$TableResDisp$ResultDiffResDisp != "NoDiff",]
Sig.2_4 <- Sig.2_4[order(Sig.2_4$ResDispDistance, decreasing = TRUE),]
Sig.2_4$Names <- mouse.genes[Sig.2_4$GeneName,2]

write.csv(Sig.2_4, "Results/Differential_testing/CD4diff/DV_day2_day4.csv")

Sig.2_7 <- Test.day2_vs_day7$TableResDisp[Test.day2_vs_day7$TableResDisp$ResultDiffResDisp != "NoDiff",]
Sig.2_7 <- Sig.2_7[order(Sig.2_7$ResDispDistance, decreasing = TRUE),]
Sig.2_7$Names <- mouse.genes[Sig.2_7$GeneName,2]

write.csv(Sig.2_7, "Results/Differential_testing/CD4diff/DV_day2_day7.csv")

Sig.4_7 <- Test.day4_vs_day7$TableResDisp[Test.day4_vs_day7$TableResDisp$ResultDiffResDisp != "NoDiff",]
Sig.4_7 <- Sig.4_7[order(Sig.4_7$ResDispDistance, decreasing = TRUE),]
Sig.4_7$Names <- mouse.genes[Sig.4_7$GeneName,2]

write.csv(Sig.4_7, "Results/Differential_testing/CD4diff/DV_day4_day7.csv")

# Write out GeneName for GO
write.table(Sig.2_4$GeneName[Sig.2_4$ResultDiffResDisp == "Day2+"], 
            "Results/Differential_testing/CD4diff/2_4_day2_genes.txt", quote = FALSE, 
            col.names = FALSE, row.names = FALSE)
write.table(Sig.2_4$GeneName[Sig.2_4$ResultDiffResDisp == "Day4+"], 
            "Results/Differential_testing/CD4diff/2_4_day4_genes.txt", quote = FALSE, 
            col.names = FALSE, row.names = FALSE)

write.table(Sig.4_7$GeneName[Sig.4_7$ResultDiffResDisp == "Day4+"], 
            "Results/Differential_testing/CD4diff/4_7_day4_genes.txt", quote = FALSE, 
            col.names = FALSE, row.names = FALSE)
write.table(Sig.4_7$GeneName[Sig.4_7$ResultDiffResDisp == "Day7+"], 
            "Results/Differential_testing/CD4diff/4_7_day7_genes.txt", quote = FALSE, 
            col.names = FALSE, row.names = FALSE)
```

First find global changes in variability

```{r}
# Find genes that are not DE in any condition
genes <- intersect(intersect(Test.day2_vs_day4.logFC0$TableDisp$GeneName, 
                   Test.day2_vs_day7.logFC0$TableDisp$GeneName),
                   Test.day4_vs_day7.logFC0$TableDisp$GeneName)

# Look at delta values for these genes
df <- data.frame(delta = c(Test.day2_vs_day4.logFC0$TableDisp$Disp2[
                             match(genes, Test.day2_vs_day4.logFC0$TableDisp$GeneName)
                             ],
                           Test.day2_vs_day4.logFC0$TableDisp$Disp1[
                             match(genes, Test.day2_vs_day4.logFC0$TableDisp$GeneName)
                             ],
                           Test.day4_vs_day7.logFC0$TableDisp$Disp1[
                             match(genes, Test.day4_vs_day7.logFC0$TableDisp$GeneName)
                           ]),
                 Day = factor(c(rep("Day 2", length(genes)), rep("Day 4", length(genes)), 
                         rep("Day 7", length(genes))), levels = c("Day 2", "Day 4", "Day 7")))

# Plot boxplot
bp.delta <- ggplot(df) + geom_boxplot(aes(Day, log(delta), fill = Day), outlier.shape = NA) +
  scale_fill_manual(values = c("#fdd49e","#ef6548" ,"#7f0000")) + theme(legend.position = 'none')
```

Now genes that show continous changes in variability or different patterns

```{r}
# Remove genes that are lowly expressed in all conditions from testing

genes <- !(is.na(MCMCs$day2@parameters$epsilon[1,]) | is.na(MCMCs$day4@parameters$epsilon[1,]) |
            is.na(MCMCs$day7@parameters$epsilon[1,]))

Test.day2_vs_day4.sets <- BASiCS_TestDE(Chain1 = MCMCs$day4, Chain2 = MCMCs$day2, 
                                   EpsilonM = 1, OffSet = TRUE, 
                                   GroupLabel2 = "Day2", GroupLabel1 = "Day4",
                                   Plot = FALSE, PlotOffset = FALSE, OrderVariable = "GeneName",
                                   GenesSelect = genes)

Test.day4_vs_day7.sets <- BASiCS_TestDE(Chain1 = MCMCs$day7, Chain2 = MCMCs$day4, 
                                   EpsilonM = 1, OffSet = TRUE, 
                                   GroupLabel2 = "Day4", GroupLabel1 = "Day7",
                                   Plot = FALSE, PlotOffset = FALSE, OrderVariable = "GeneName",
                                   GenesSelect = genes)

# 1st: up-up
genenames <- intersect(
  Test.day2_vs_day4.sets$TableResDisp$GeneName[Test.day2_vs_day4.sets$TableResDisp$ResultDiffResDisp == "Day4+"],
  Test.day4_vs_day7.sets$TableResDisp$GeneName[Test.day4_vs_day7.sets$TableResDisp$ResultDiffResDisp == "Day7+"]
)

cur_df <- data.frame(epsilon = c(Test.day2_vs_day4.sets$TableResDisp$ResDisp2[
                             match(genenames,Test.day2_vs_day4.sets$TableResDisp$GeneName)
                           ],
                           Test.day2_vs_day4.sets$TableResDisp$ResDisp1[
                             match(genenames,Test.day2_vs_day4.sets$TableResDisp$GeneName)
                           ],
                           Test.day4_vs_day7.sets$TableResDisp$ResDisp1[
                             match(genenames,Test.day4_vs_day7.sets$TableResDisp$GeneName )
                           ]),
                 Day = factor(c(rep("Day 2", length(genenames)), rep("Day 4", length(genenames)), 
                         rep("Day 7", length(genenames))), levels = c("Day 2", "Day 4", "Day 7")),
                 Genes = rep(genenames, 3)) 

plot.1 <- ggplot(cur_df, aes(group = Genes)) + 
  geom_line(aes(x = Day, y = epsilon, alpha = 0.3)) +
  theme(legend.position = 'none', axis.title.x = element_blank()) +
  scale_x_discrete(expand=c(0.05,0.05)) +
  annotate("text", x=2.5, y=4, label= paste(length(genenames), " genes", sep = ""), size = 5) 

write.table(genenames, 
            "Results/Differential_testing/CD4diff/Up-Up.txt", quote = FALSE, 
            col.names = FALSE, row.names = FALSE)

# 2nd: down-down
genenames <- intersect(
  Test.day2_vs_day4.sets$TableResDisp$GeneName[Test.day2_vs_day4.sets$TableResDisp$ResultDiffResDisp == "Day2+"],
  Test.day4_vs_day7.sets$TableResDisp$GeneName[Test.day4_vs_day7.sets$TableResDisp$ResultDiffResDisp == "Day4+"]
)

cur_df <- data.frame(epsilon = c(Test.day2_vs_day4.sets$TableResDisp$ResDisp2[
                             match(genenames,Test.day2_vs_day4.sets$TableResDisp$GeneName)
                           ],
                           Test.day2_vs_day4.sets$TableResDisp$ResDisp1[
                             match(genenames,Test.day2_vs_day4.sets$TableResDisp$GeneName)
                           ],
                           Test.day4_vs_day7.sets$TableResDisp$ResDisp1[
                             match(genenames,Test.day4_vs_day7.sets$TableResDisp$GeneName )
                           ]),
                 Day = factor(c(rep("Day 2", length(genenames)), rep("Day 4", length(genenames)), 
                         rep("Day 7", length(genenames))), levels = c("Day 2", "Day 4", "Day 7")),
                 Genes = rep(genenames, 3)) 

plot.2 <- ggplot(cur_df, aes(group = Genes)) + 
  geom_line(aes(x = Day, y = epsilon, alpha = 0.3)) +
  theme(legend.position = 'none', axis.title.x = element_blank()) +
  scale_x_discrete(expand=c(0.05,0.05)) +
  annotate("text", x=2.5, y=4, label= paste(length(genenames), " genes", sep = ""), size = 5) 

write.table(genenames, 
            "Results/Differential_testing/CD4diff/Down-Down.txt", quote = FALSE, 
            col.names = FALSE, row.names = FALSE)

# 3rd: down-up
genenames <- intersect(
  Test.day2_vs_day4.sets$TableResDisp$GeneName[Test.day2_vs_day4.sets$TableResDisp$ResultDiffResDisp == "Day2+"],
  Test.day4_vs_day7.sets$TableResDisp$GeneName[Test.day4_vs_day7.sets$TableResDisp$ResultDiffResDisp == "Day7+"]
)

cur_df <- data.frame(epsilon = c(Test.day2_vs_day4.sets$TableResDisp$ResDisp2[
                             match(genenames,Test.day2_vs_day4.sets$TableResDisp$GeneName)
                           ],
                           Test.day2_vs_day4.sets$TableResDisp$ResDisp1[
                             match(genenames,Test.day2_vs_day4.sets$TableResDisp$GeneName)
                           ],
                           Test.day4_vs_day7.sets$TableResDisp$ResDisp1[
                             match(genenames,Test.day4_vs_day7.sets$TableResDisp$GeneName )
                           ]),
                 Day = factor(c(rep("Day 2", length(genenames)), rep("Day 4", length(genenames)), 
                         rep("Day 7", length(genenames))), levels = c("Day 2", "Day 4", "Day 7")),
                 Genes = rep(genenames, 3)) 

plot.3 <- ggplot(cur_df, aes(group = Genes)) + 
  geom_line(aes(x = Day, y = epsilon, alpha = 0.3)) +
  theme(legend.position = 'none', axis.title.x = element_blank()) +
  scale_x_discrete(expand=c(0.05,0.05)) +
  annotate("text", x=2.5, y=4, label= paste(length(genenames), " genes", sep = ""), size = 5) 

write.table(genenames, 
            "Results/Differential_testing/CD4diff/Down-Up.txt", quote = FALSE, 
            col.names = FALSE, row.names = FALSE)

# 4th: up-down
genenames <- intersect(
  Test.day2_vs_day4.sets$TableResDisp$GeneName[Test.day2_vs_day4.sets$TableResDisp$ResultDiffResDisp == "Day4+"],
  Test.day4_vs_day7.sets$TableResDisp$GeneName[Test.day4_vs_day7.sets$TableResDisp$ResultDiffResDisp == "Day4+"]
)

cur_df <- data.frame(epsilon = c(Test.day2_vs_day4.sets$TableResDisp$ResDisp2[
                             match(genenames,Test.day2_vs_day4.sets$TableResDisp$GeneName)
                           ],
                           Test.day2_vs_day4.sets$TableResDisp$ResDisp1[
                             match(genenames,Test.day2_vs_day4.sets$TableResDisp$GeneName)
                           ],
                           Test.day4_vs_day7.sets$TableResDisp$ResDisp1[
                             match(genenames,Test.day4_vs_day7.sets$TableResDisp$GeneName )
                           ]),
                 Day = factor(c(rep("Day 2", length(genenames)), rep("Day 4", length(genenames)), 
                         rep("Day 7", length(genenames))), levels = c("Day 2", "Day 4", "Day 7")),
                 Genes = rep(genenames, 3)) 

plot.4 <- ggplot(cur_df, aes(group = Genes)) + 
  geom_line(aes(x = Day, y = epsilon, alpha = 0.3)) +
  theme(legend.position = 'none', axis.title.x = element_blank()) +
  scale_x_discrete(expand=c(0.05,0.05)) +
  annotate("text", x=2.5, y=4, label= paste(length(genenames), " genes", sep = ""), size = 5) 

write.table(genenames, 
            "Results/Differential_testing/CD4diff/Up-Down.txt", quote = FALSE, 
            col.names = FALSE, row.names = FALSE)

dist.plot <- plot_grid(plot.1, plot.2, plot.3, plot.4, ncol = 2, nrow = 2, align = 'hv')

```

Now look at single genes

```{r}
# Normalize data
input <- read.table("../Data/Test_Data/CD4_diff.txt", sep = "\t")

#### Read in Spike-ins
ERCC.conc <- read.table("../Data/Raw_data/CD4_Diff/ERCC_malaria.txt", header=TRUE, sep = "\t", fill = TRUE)

ERCC.num <- matrix(data=NA, nrow=nrow(ERCC.conc), ncol=1)
ERCC.num[,1] <- (ERCC.conc[,2]*(10^(-18)))*(6.0221417*(10^23))
rownames(ERCC.num) <- ERCC.conc[,1]

SpikeInput <- ERCC.num[rownames(input)[grepl("ERCC", rownames(input))],1]
SpikeInput.1 <- data.frame("Name" = names(SpikeInput),
                           "Molecules" = SpikeInput,
                           stringsAsFactors = FALSE)

#### Create Data objects for each condition
cur_input <- input[,grepl("2_", colnames(input))]
cur_chips <- sapply(colnames(cur_input), function(n){unlist(strsplit(n, "\\."))[1]})
Data.Day2 <- newBASiCS_Data(Counts = cur_input, 
                            Tech = grepl("ERCC", rownames(input)), 
                            SpikeInfo = SpikeInput.1, 
                            BatchInfo = cur_chips)

cur_input <- input[,grepl("4_", colnames(input))]
cur_chips <- sapply(colnames(cur_input), function(n){unlist(strsplit(n, "\\."))[1]})
Data.Day4 <- newBASiCS_Data(Counts = cur_input, 
                            Tech = grepl("ERCC", rownames(input)), 
                            SpikeInfo = SpikeInput.1, 
                            BatchInfo = cur_chips)

# Offset correction
OffSet <- function(MCMC1, MCMC2){
  OS <- median(rowSums(MCMC1@parameters$mu)/rowSums(MCMC2@parameters$mu))
  OS
}

OS <- OffSet(MCMCs$day2, MCMCs$day4)

MCMCs$day2@parameters$mu <- MCMCs$day2@parameters$mu / OS
MCMCs$day2@parameters$phi <- MCMCs$day2@parameters$phi * OS

Counts.day2 <- BASiCS_DenoisedCounts(Data.Day2, MCMCs$day2)
Counts.day4 <- BASiCS_DenoisedCounts(Data.Day4, MCMCs$day4)

rownames(Counts.day2) <- mouse.genes[rownames(Counts.day2),2]
rownames(Counts.day4) <- mouse.genes[rownames(Counts.day4),2]

# Cxcr5 - Day4
df.gene <- data.frame(value = c(log10(Counts.day2["Cxcr5",] + 1),
                                log10(Counts.day4["Cxcr5",] + 1)),
                      Day = factor(c(rep("Day 2", ncol(Counts.day2)), 
                                      rep("Day 4", ncol(Counts.day4))),
                                    levels= c("Day 2", "Day 4")))

jitter.Cxcr5 <- ggplot(df.gene, aes(Day, value)) + 
  geom_boxplot(aes(fill = Day), alpha = 0.3, outlier.shape = NA, width=0.25)+
  geom_jitter(aes(fill = Day), width=0.25, shape=21) + ylab("log10(Cxcr5 expr)") + xlab("") +
  scale_color_manual(values = c("#fdd49e", "#ef6548")) + scale_fill_manual(values = c("#fdd49e", "#ef6548")) +
  theme(legend.position=c(0,1), legend.justification=c(0,1))+ ylim(c(-0.1,6.5))

# Tigit - Day4
df.gene <- data.frame(value = c(log10(Counts.day2["Tigit",] + 1),
                                log10(Counts.day4["Tigit",] + 1)),
                      Day = factor(c(rep("Day 2", ncol(Counts.day2)), 
                                      rep("Day 4", ncol(Counts.day4))),
                                    levels= c("Day 2", "Day 4")))

jitter.Tigit <- ggplot(df.gene, aes(Day, value)) + 
  geom_boxplot(aes(fill = Day), alpha = 0.3, outlier.shape = NA, width=0.25)+
  geom_jitter(aes(fill = Day), width=0.25, shape=21) + ylab("log10(Tigit expr)") + xlab("") +
  scale_color_manual(values = c("#fdd49e", "#ef6548")) + scale_fill_manual(values = c("#fdd49e", "#ef6548")) +
  theme(legend.position='none', legend.justification=c(0,1))+ ylim(c(-0.1,6.5))

# Tyk2 - Day4
df.gene <- data.frame(value = c(log10(Counts.day2["Tyk2",] + 1),
                                log10(Counts.day4["Tyk2",] + 1)),
                      Day = factor(c(rep("Day 2", ncol(Counts.day2)), 
                                      rep("Day 4", ncol(Counts.day4))),
                                    levels= c("Day 2", "Day 4")))

jitter.Tyk2 <- ggplot(df.gene, aes(Day, value)) + 
  geom_boxplot(aes(fill = Day), alpha = 0.3, outlier.shape = NA, width=0.25)+
  geom_jitter(aes(fill = Day), width=0.25, shape=21) + ylab("log10(Tyk2 expr)") + xlab("") +
  scale_color_manual(values = c("#fdd49e", "#ef6548")) + scale_fill_manual(values = c("#fdd49e", "#ef6548")) +
  theme(legend.position='none', legend.justification=c(0,1))+ ylim(c(-0.1,6.5))

# Ikzf4 - Day 2
df.gene <- data.frame(value = c(log10(Counts.day2["Ikzf4",] + 1),
                                log10(Counts.day4["Ikzf4",] + 1)),
                      Day = factor(c(rep("Day 2", ncol(Counts.day2)), 
                                      rep("Day 4", ncol(Counts.day4))),
                                    levels= c("Day 2", "Day 4")))

jitter.Ikzf4 <- ggplot(df.gene, aes(Day, value)) + 
  geom_boxplot(aes(fill = Day), alpha = 0.3, outlier.shape = NA, width=0.25)+
  geom_jitter(aes(fill = Day), width=0.25, shape=21) + ylab("log10(Ikzf4 expr)") + xlab("") +
  scale_color_manual(values = c("#fdd49e", "#ef6548")) + scale_fill_manual(values = c("#fdd49e", "#ef6548")) +
  theme(legend.position='none', legend.justification=c(0,1))+ ylim(c(-0.1,6.5))

# Ly6c1 - Day 2
df.gene <- data.frame(value = c(log10(Counts.day2["Ly6c1",] + 1),
                                log10(Counts.day4["Ly6c1",] + 1)),
                      Day = factor(c(rep("Day 2", ncol(Counts.day2)), 
                                      rep("Day 4", ncol(Counts.day4))),
                                    levels= c("Day 2", "Day 4")))

jitter.Ly6c1 <- ggplot(df.gene, aes(Day, value)) + 
  geom_boxplot(aes(fill = Day), alpha = 0.3, outlier.shape = NA, width=0.25)+
  geom_jitter(aes(fill = Day), width=0.25, shape=21) + ylab("log10(Ly6c1 expr)") + xlab("") +
  scale_color_manual(values = c("#fdd49e", "#ef6548")) + scale_fill_manual(values = c("#fdd49e", "#ef6548")) +
  theme(legend.position='none', legend.justification=c(0,1))+ ylim(c(-0.1,6.5))

# Tbx21 - Day 2
df.gene <- data.frame(value = c(log10(Counts.day2["Tbx21",] + 1),
                                log10(Counts.day4["Tbx21",] + 1)),
                      Day = factor(c(rep("Day 2", ncol(Counts.day2)), 
                                      rep("Day 4", ncol(Counts.day4))),
                                    levels= c("Day 2", "Day 4")))

jitter.Tbx21 <- ggplot(df.gene, aes(Day, value)) + 
  geom_boxplot(aes(fill = Day), alpha = 0.3, outlier.shape = NA, width=0.25)+
  geom_jitter(aes(fill = Day), width=0.25, shape=21) + ylab("log10(Tbx21 expr)") + xlab("") +
  scale_color_manual(values = c("#fdd49e", "#ef6548")) + scale_fill_manual(values = c("#fdd49e", "#ef6548")) +
  theme(legend.position='none', legend.justification=c(0,1)) + ylim(c(-0.1,6.5))

# Ratio of Tbx21 cells
length(which(Counts.day2["Tbx21",] > 0))/ncol(Counts.day2)

jitter.final <- plot_grid(jitter.Cxcr5, jitter.Tigit, jitter.Tyk2, 
                          jitter.Ikzf4, jitter.Ly6c1, jitter.Tbx21,
                          align = "hv", nrow = 2, ncol = 3, labels = c("C", NA, NA, "D", NA, NA))

```

Visualize marker genes through DE DV space.

```{r}
genes <- c("Cxcr5", "Tbx21")
rownames(Test.day2_vs_day4$TableResDisp) <- mouse.genes[Test.day2_vs_day4$TableResDisp$GeneName,2]
rownames(Test.day2_vs_day4$TableMean) <-  mouse.genes[Test.day2_vs_day4$TableMean$GeneName,2]
rownames(Test.day4_vs_day7$TableResDisp) <- mouse.genes[Test.day4_vs_day7$TableResDisp$GeneName,2]
rownames(Test.day4_vs_day7$TableMean) <- mouse.genes[Test.day4_vs_day7$TableMean$GeneName,2]
rownames(Test.day2_vs_day7$TableResDisp) <- mouse.genes[Test.day2_vs_day7$TableResDisp$GeneName,2]
rownames(Test.day2_vs_day7$TableMean) <- mouse.genes[Test.day2_vs_day7$TableMean$GeneName,2]

df <- data.frame(mu = c(Test.day2_vs_day4$TableMean[genes,"Mean2"],
                        Test.day2_vs_day4$TableMean[genes,"Mean1"],
                        Test.day2_vs_day7$TableMean[genes,"Mean1"]),
                 epsilon = c(Test.day2_vs_day4$TableResDisp[genes,"ResDisp2"],
                        Test.day2_vs_day4$TableResDisp[genes,"ResDisp1"],
                        Test.day2_vs_day7$TableResDisp[genes,"ResDisp1"]),
                 Genes = factor(rep(genes, 3)),
                 Day = factor(rep(c("Day 2", "Day 4", "Day 7"), each = 2)))

df.arrows <- data.frame(x = df[1:4,1],
                        y = df[1:4,2],
                        xend = df[3:6,1],
                        yend = df[3:6,2],
                        Genes = rep(genes, 2))

trace.plot <- ggplot(df) + 
  scale_colour_manual(values = setNames(c("indianred4", "royalblue4"), 
                                        c("Cxcr5", "Tbx21"))) + 
  geom_segment(data=df.arrows, 
        aes(x=log(x), y=y, xend=log(xend), yend=yend, colour = Genes),
        lineend="round",arrow=arrow(length=unit(0.2, "inches")), size=2) + xlab("log(Expr)") + ylab("Epsilon \n Less variable <-> More variable")

# Final figure
final <- plot_grid(bp.delta, dist.plot, jitter.final, trace.plot, ncol = 2, nrow = 2,
                   labels = c("A", "B", NA, "D"))

ggsave("Manuscript/Figures/Fig4.pdf", plot = final, width = 10, height = 10)

```
