---
title: "Fig4_datasets"
author: "Nils Eling"
date: "30/08/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Test on a variety of datasets

Here we use different (UMI and non-UMI) scRNAseq datasets to visualize and assess the regression case of BASiCS.

```{r}
library(BASiCS)
library(coda)
library(cowplot)
MCMCs <- readRDS("Results/Testing/Tdist/All_datasets.rds")

# CD4 T cells

# Mean vs over-dispersion plot for non-regression model
CD4.old <- ggplot(data.frame(mu = colMedians(MCMCs$MCMC_CD4_old.rds@parameters$mu),
                             delta = colMedians(MCMCs$MCMC_CD4_old.rds@parameters$delta))) + 
  geom_hex(aes(log(mu), log(delta)), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("log(mu)") + ylab("log(delta)") + theme_minimal(base_size = 15) + ylim(c(-2.5,10)) + xlim(c(-2.5, 13))

# Mean vs over-dispersion plot for regression model
CD4.new <- showFit(MCMCs$MCMC_CD4_12_1.2_5_reg.rds) + ylim(c(-2.5,10)) + xlim(c(-2.5, 13))

# Mean vs residual over-dispersion plot for regression model
CD4.epsilon <- ggplot(data.frame(mu = colMedians(MCMCs$MCMC_CD4_12_1.2_5_reg.rds@parameters$mu),
                             epsilon = colMedians(MCMCs$MCMC_CD4_12_1.2_5_reg.rds@parameters$epsilon))) + 
  geom_hex(aes(log(mu), epsilon), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("log(mu)") + ylab("epsilon") + theme_minimal(base_size = 15) + 
  geom_abline(slope = 0, intercept = 0, col="dark red")

# Mean vs dropout rate plot for regression model
input.CD4 <- read.table("/Users/eling01/Google Drive/BASiCS_add-on/Data/Test_Data/CD4_NaiveActiveYoungB6.txt",
                        sep="\t")
input.CD4 <- input.CD4[!grepl("ERCC", rownames(input.CD4)),grepl("naive", colnames(input.CD4))]

CD4.dropout <- ggplot(data.frame(epsilon = colMedians(MCMCs$MCMC_CD4_12_1.2_5_reg.rds@parameters$epsilon),
                             dropout = apply(input.CD4, 1, function(n){length(which(n == 0))/length(n)}))) + 
  geom_hex(aes(dropout, epsilon), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("Droput rate") + ylab("epsilon") + theme_minimal(base_size = 15) + 
  geom_abline(slope = 0, intercept = 0, col="dark red")

# Zeisel data

# Mean vs over-dispersion plot for non-regression model
Zeisel.old <- ggplot(data.frame(mu = colMedians(MCMCs$MCMC_Zeisel_old.rds@parameters$mu),
                             delta = colMedians(MCMCs$MCMC_Zeisel_old.rds@parameters$delta))) + 
  geom_hex(aes(log(mu), log(delta)), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("log(mu)") + ylab("log(delta)") + theme_minimal(base_size = 15) + ylim(c(-2.5,7)) + xlim(c(-2.5, 8))

# Mean vs over-dispersion plot for regression model
Zeisel.new <- showFit(MCMCs$MCMC_Zeisel_12_1.2_5_reg.rds) + ylim(c(-2.5,7)) + xlim(c(-2.5, 8))

# Mean vs residual over-dispersion plot for regression model
Zeisel.epsilon <- ggplot(data.frame(mu = colMedians(MCMCs$MCMC_Zeisel_12_1.2_5_reg.rds@parameters$mu),
                             epsilon = colMedians(MCMCs$MCMC_Zeisel_12_1.2_5_reg.rds@parameters$epsilon))) + 
  geom_hex(aes(log(mu), epsilon), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("log(mu)") + ylab("epsilon") + theme_minimal(base_size = 15) + 
  geom_abline(slope = 0, intercept = 0, col="dark red")

# Mean vs dropout rate plot for regression model
input.Zeisel <- read.table("/Users/eling01/Google Drive/BASiCS_add-on/Data/Test_Data/microglia_Zeisel.txt",
                        sep="\t")
input.Zeisel <- input.Zeisel[!grepl("ERCC", rownames(input.Zeisel)),]

Zeisel.dropout <- ggplot(data.frame(epsilon = colMedians(MCMCs$MCMC_Zeisel_12_1.2_5_reg.rds@parameters$epsilon),
                             dropout = apply(input.Zeisel, 1, function(n){length(which(n == 0))/length(n)}))) + 
  geom_hex(aes(dropout, epsilon), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("Droput rate") + ylab("epsilon") + theme_minimal(base_size = 15) + 
  geom_abline(slope = 0, intercept = 0, col="dark red")

# Pool-split data

# Mean vs over-dispersion plot for non-regression model
RNA.old <- ggplot(data.frame(mu = colMedians(MCMCs$MCMC_RNA_old.rds@parameters$mu),
                             delta = colMedians(MCMCs$MCMC_RNA_old.rds@parameters$delta))) + 
  geom_hex(aes(log(mu), log(delta)), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("log(mu)") + ylab("log(delta)") + theme_minimal(base_size = 15) + ylim(c(-7,1.5)) + xlim(c(0, 10))

# Mean vs over-dispersion plot for regression model
RNA.new <- showFit(MCMCs$MCMC_RNA_12_1.2_5_reg.rds) + ylim(c(-7,1.5)) + xlim(c(0, 10))

# Mean vs residual over-dispersion plot for regression model
RNA.epsilon <- ggplot(data.frame(mu = colMedians(MCMCs$MCMC_RNA_12_1.2_5_reg.rds@parameters$mu),
                             epsilon = colMedians(MCMCs$MCMC_RNA_12_1.2_5_reg.rds@parameters$epsilon))) + 
  geom_hex(aes(log(mu), epsilon), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("log(mu)") + ylab("epsilon") + theme_minimal(base_size = 15) + 
  geom_abline(slope = 0, intercept = 0, col="dark red")

# Mean vs dropout rate plot for regression model
input.RNA <- read.table("/Users/eling01/Google Drive/BASiCS_add-on/Data/Test_Data/PoolSplit.txt",
                        sep="\t")
input.RNA <- input.RNA[!grepl("ERCC", rownames(input.RNA)),grepl("RNA", colnames(input.RNA))]

RNA.dropout <- ggplot(data.frame(epsilon = colMedians(MCMCs$MCMC_RNA_12_1.2_5_reg.rds@parameters$epsilon),
                             dropout = apply(input.RNA, 1, function(n){length(which(n == 0))/length(n)}))) + 
  geom_hex(aes(dropout, epsilon), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("Droput rate") + ylab("epsilon") + theme_minimal(base_size = 15) + 
  geom_abline(slope = 0, intercept = 0, col="dark red")

# Dict data

# Mean vs over-dispersion plot for non-regression model
Dict.old <- ggplot(data.frame(mu = colMedians(MCMCs$MCMC_Dict_old.rds@parameters$mu),
                             delta = colMedians(MCMCs$MCMC_Dict_old.rds@parameters$delta))) + 
  geom_hex(aes(log(mu), log(delta)), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("log(mu)") + ylab("log(delta)") + theme_minimal(base_size = 15) + ylim(c(-5,12)) + xlim(c(-3, 17))

# Mean vs over-dispersion plot for regression model
Dict.new <- showFit(MCMCs$MCMC_Dict_12_1.2_5_reg.rds) + ylim(c(-5,12)) + xlim(c(-3, 17))

# Mean vs residual over-dispersion plot for regression model
Dict.epsilon <- ggplot(data.frame(mu = colMedians(MCMCs$MCMC_Dict_12_1.2_5_reg.rds@parameters$mu),
                             epsilon = colMedians(MCMCs$MCMC_Dict_12_1.2_5_reg.rds@parameters$epsilon))) + 
  geom_hex(aes(log(mu), epsilon), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("log(mu)") + ylab("epsilon") + theme_minimal(base_size = 15) + 
  geom_abline(slope = 0, intercept = 0, col="dark red")

# Mean vs dropout rate plot for regression model
input.Dict <- read.table("/Users/eling01/Google Drive/BASiCS_add-on/Data/Test_Data/Dictyostelium.txt",
                        sep="\t")
input.Dict <- input.Dict[!grepl("ERCC", rownames(input.Dict)),grepl("X0h", colnames(input.Dict))]

Dict.dropout <- ggplot(data.frame(epsilon = colMedians(MCMCs$MCMC_Dict_12_1.2_5_reg.rds@parameters$epsilon),
                             dropout = apply(input.Dict, 1, function(n){length(which(n == 0))/length(n)}))) + 
  geom_hex(aes(dropout, epsilon), bins = 100) +
  scale_fill_gradientn("", colours = colorRampPalette(c("dark blue", "yellow", "dark red"))(100), guide=FALSE) +
  xlab("Droput rate") + ylab("epsilon") + theme_minimal(base_size = 15) + 
  geom_abline(slope = 0, intercept = 0, col="dark red")



final <- plot_grid(CD4.old, CD4.new, CD4.epsilon, CD4.dropout, 
                   Zeisel.old, Zeisel.new, Zeisel.epsilon, Zeisel.dropout, 
                   Dict.old, Dict.new, Dict.epsilon, Dict.dropout, 
                   RNA.old, RNA.new, RNA.epsilon, RNA.dropout, ncol = 4,
                   nrow =4, align = "hv", labels = "AUTO")

ggsave(filename = "Manuscript/Figures/FigS6.pdf", plot = final,  width = 15, height = 27, dpi=600)
```