#!/usr/bin/env bash

#MAXCOUNT=80
#count=1

#while [ "$count" -le $MAXCOUNT ]; 
#do
# seedlist[$count]=$RANDOM
# let "count += 1"
#done

#count=1

#celllist=(50 100 150 200 250 300 500)
#itlist=(1 2 3 4 5 6 7 8 9 10)
#for i in ${celllist[@]};
#do
#	for j in ${itlist[@]};
#	do
#		Scripts/bsub -M 4000 Rscript Scripts/Single_runs/downsampling_Zeisel_new.R $i $j ${seedlist[$count]}
#		Scripts/bsub -M 4000 Rscript Scripts/Single_runs/downsampling_Zeisel_old.R $i $j ${seedlist[$count]}
#		let "count += 1"
#	done
#done
#Scripts/bsub -M 4000 Rscript Scripts/Single_runs/downsampling_Zeisel_new.R 939 1 12
#Scripts/bsub -M 4000 Rscript Scripts/Single_runs/downsampling_Zeisel_old.R 939 1 12



MAXCOUNT=80
count=1

while [ "$count" -le $MAXCOUNT ];
do
 seedlist[$count]=$RANDOM
 let "count += 1"
done

count=1

celllist=(40 60 80 100 120 160 200)
itlist=(1 2 3 4 5 6 7 8 9 10)
for i in ${celllist[@]};
do
        for j in ${itlist[@]};
        do
                Scripts/bsub -M 4000 Rscript Scripts/Single_runs/downsampling_CD4_new.R $i $j ${seedlist[$count]}
                Scripts/bsub -M 4000 Rscript Scripts/Single_runs/downsampling_CD4_old.R $i $j ${seedlist[$count]}
                let "count += 1"
        done
done
Scripts/bsub -M 4000 Rscript Scripts/Single_runs/downsampling_CD4_new.R 215 1 12
Scripts/bsub -M 4000 Rscript Scripts/Single_runs/downsampling_CD4_old.R 215 1 12
