#!/usr/bin/env bash

# Script to subset varying numbers of cells from the CA1 pyramidal neuron population.
# Random seeds are generated to run the regression and non-regression model on the cell population.
# The batch job works on a lsf system.

MAXCOUNT=80
count=1

while [ "$count" -le $MAXCOUNT ]; 
do
 seedlist[$count]=$RANDOM
 let "count += 1"
done

count=1

celllist=(50 100 150 200 250 300 500)
itlist=(1 2 3 4 5 6 7 8 9 10)
for i in ${celllist[@]};
do
	for j in ${itlist[@]};
	do
		bsub -M 4000 Rscript downsampling_Zeisel_new.R $i $j ${seedlist[$count]}
		bsub -M 4000 Rscript downsampling_Zeisel_old.R $i $j ${seedlist[$count]}
		let "count += 1"
	done
done
bsub -M 4000 Rscript downsampling_Zeisel_new.R 939 1 12
bsub -M 4000 Rscript downsampling_Zeisel_old.R 939 1 12


